# Generated by Django 3.2.6 on 2021-10-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210910_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeTest',
        ),
    ]
