# Generated by Django 3.2.6 on 2021-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('work_begin', models.DateField(blank=True, null=True)),
                ('work_end', models.DateField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'work_time',
                'managed': False,
            },
        ),
    ]
